UNIX_TEMPLATES = [
    {"id":"UNIX-01","title":"Count total records","priority":"Must Have",
     "story":"As a data engineer at {org}, I want to count the total number of {entity} records so that I can validate the row count before starting the data pipeline.",
     "command":"tail -n +2 {file} | wc -l",
     "note":"Skips the header row. Output is the total number of data rows."},
    {"id":"UNIX-02","title":"Display file header","priority":"Must Have",
     "story":"As a developer at {org}, I want to view the column headers of the {entity} file so that I understand the schema before writing processing scripts.",
     "command":"head -1 {file}",
     "note":"Displays only the first line (the header)."},
    {"id":"UNIX-03","title":"Filter Active records","priority":"Must Have",
     "story":"As a business analyst at {org}, I want to extract all {entity} records where status is Active so that I can build reports on currently operational entries.",
     "command":"grep -i ',Active,' {file} > active_{file}",
     "note":"Case-insensitive match. Adjust the column surrounding Active if needed."},
    {"id":"UNIX-04","title":"Extract specific columns","priority":"Must Have",
     "story":"As a reporting analyst at {org}, I want to extract only the ID and name columns from the {entity} dataset so that I can generate a lightweight summary.",
     "command":"cut -d',' -f1,2 {file} | head -50",
     "note":"Adjust -f column numbers to match ID and name column positions."},
    {"id":"UNIX-05","title":"Sort by amount descending","priority":"Must Have",
     "story":"As a finance lead at {org}, I want to sort all {entity} records by the amount field descending so that I can identify the highest-value entries.",
     "command":"tail -n +2 {file} | sort -t',' -k4 -rn | head -20",
     "note":"Adjust -k to match the column index of the amount field."},
    {"id":"UNIX-06","title":"Count unique status values","priority":"Must Have",
     "story":"As a quality analyst at {org}, I want to count all distinct status values in the {entity} dataset so that I can detect any unexpected entries.",
     "command":"tail -n +2 {file} | cut -d',' -f$(head -1 {file} | tr ',' '\\n' | grep -n 'status' | cut -d: -f1) | sort | uniq -c | sort -rn",
     "note":"Dynamically detects the status column and produces a frequency table."},
    {"id":"UNIX-07","title":"Find rows with missing fields","priority":"Must Have",
     "story":"As a data quality engineer at {org}, I want to identify all {entity} records with empty or NULL values so that I can flag them for remediation.",
     "command":"awk -F',' '{for(i=1;i<=NF;i++) if($i==\"\" || $i==\"NULL\") {print NR\": field \"i\" empty\"; break}}' {file}",
     "note":"Prints row number and field index for every row with an issue."},
    {"id":"UNIX-08","title":"Calculate field average","priority":"Must Have",
     "story":"As a finance analyst at {org}, I want to calculate the average value of the amount field across all {entity} records so that I can establish a financial baseline.",
     "command":"tail -n +2 {file} | awk -F',' '{sum+=$4;count++} END{printf \"Average: %.2f\\n\",sum/count}'",
     "note":"Replace $4 with the actual column index of the amount field."},
    {"id":"UNIX-09","title":"Detect duplicate IDs","priority":"Must Have",
     "story":"As a data integrity officer at {org}, I want to detect duplicate {entity} IDs so that I can ensure primary key uniqueness before database loading.",
     "command":"tail -n +2 {file} | cut -d',' -f1 | sort | uniq -d",
     "note":"Shows only values that appear more than once in column 1 (ID)."},
    {"id":"UNIX-10","title":"Filter by date range","priority":"Must Have",
     "story":"As an operations manager at {org}, I want to filter all {entity} records between 2023-01-01 and 2023-12-31 so that I can generate the annual report.",
     "command":"awk -F',' '$6 >= \"2023-01-01\" && $6 <= \"2023-12-31\" {print}' {file}",
     "note":"Replace $6 with the actual date column index. Dates must be YYYY-MM-DD."},
    {"id":"UNIX-11","title":"Display top 10 by value","priority":"Should Have",
     "story":"As a strategic analyst at {org}, I want the top 10 {entity} records ranked by amount so that I can present a priority list to leadership.",
     "command":"tail -n +2 {file} | sort -t',' -k4 -rn | head -10",
     "note":"Change -k to the correct amount column index."},
    {"id":"UNIX-12","title":"Replace invalid values","priority":"Should Have",
     "story":"As a data remediation engineer at {org}, I want to replace N/A##INVALID with UNKNOWN in the {entity} file so that downstream pipelines do not fail.",
     "command":"sed -i 's/N\\/A##INVALID/UNKNOWN/g' {file}",
     "note":"In-place replacement. On macOS: sed -i '' 's/.../' file"},
    {"id":"UNIX-13","title":"File size audit","priority":"Should Have",
     "story":"As a system administrator at {org}, I want to audit the size of all entity data files so that I can plan storage capacity.",
     "command":"wc -l *.csv 2>/dev/null; du -sh datasets/generated/*/",
     "note":"wc -l gives line counts; du -sh gives human-readable folder sizes."},
    {"id":"UNIX-14","title":"Find recently modified files","priority":"Should Have",
     "story":"As a data operations lead at {org}, I want to list dataset files modified in the last 7 days so that I can track recent data loads.",
     "command":"find datasets/ \\( -name '*.csv' -o -name '*.json' \\) -mtime -7 | xargs ls -lt",
     "note":"Sorted by modification time, newest first."},
    {"id":"UNIX-15","title":"Search for corrupt markers","priority":"Could Have",
     "story":"As a compliance officer at {org}, I want to search all {entity} files for CORRUPT or INVALID markers so that I can produce a data quality report.",
     "command":"grep -rl 'CORRUPT\\|INVALID\\|##' datasets/ | while read f; do echo \"$f: $(grep -c 'CORRUPT\\|INVALID\\|##' $f) issues\"; done",
     "note":"Recursively searches all files and reports count of issues per file."},
]

def generate_unix_stories(entity_config, sector_data):
    org    = sector_data.get("business_context", sector_data["display"] + " Organisation").split(",")[0]
    entity = entity_config["name"]
    file_  = f"{entity.lower()}.{entity_config['format']}"
    return [
        {
            "id":       t["id"],
            "title":    t["title"],
            "priority": t["priority"],
            "story":    t["story"].format(org=org, entity=entity),
            "command":  t["command"].replace("{file}", file_),
            "note":     t["note"],
        }
        for t in UNIX_TEMPLATES
    ]